version: '2.2'

services:
  db1:
    container_name: mssql-server-samplesdb
    build:
      context: .
      dockerfile: Dockerfile-prepared-for-registry
    hostname:
        mssql-server
    domainname:
        enriquecatala.com    
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      FORCE_ATTACH_IF_MDF_EXISTS: "0"
    #volumes:
    #  - ${LOCAL_MOUNTPOINT}:/var/opt/mssql/data
    ports:
      - "14330:1433"
    mem_limit: 8Gb
    cpu_count: 4
