version: '2.4'

services:
  db1:
    container_name: mssql-server-samplesdb
    build:
      context: .
      dockerfile: Dockerfile
    hostname:
        mssql-samplesdb
    domainname:
        enriquecatala.com    
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      FORCE_ATTACH_IF_MDF_EXISTS: "${FORCE_ATTACH_IF_MDF_EXISTS}"      
    volumes:
       - ${LOCAL_MOUNTPOINT}:/var/opt/mssql/data
    ports:
      - "14330:1433"
    # https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources
    # user: "10001:0"        
    cpu_count: 4
    mem_limit: 8Gb
    
