version: '2.4'

services:
  db1:
    container_name: mssql-server-samplesdb
    build:
      context: .
      dockerfile: Dockerfile
    hostname:
        mssql-samplesdb
    domainname:
        enriquecatala.com        
    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"
      FORCE_ATTACH_IF_MDF_EXISTS: "${FORCE_ATTACH_IF_MDF_EXISTS}"    
      INCLUDE_ALL_DATABASES: "${INCLUDE_ALL_DATABASES}"      
    volumes:
      - ${LOCAL_MOUNTPOINT}:/var/opt/mssql/data
      - ${SHARED_FOLDER}:/var/opt/mssql/shared_folder      
      - ./Backups:/var/opt/mssql/backup
    ports:
      - "14330:1433"        
    cpu_count: 4
    mem_limit: 8Gb
    
